version: '3.8'
services:
  app:
    image: "fhsshim/amihired-app"
    mem_limit: 512m
  proxy:
    image: "fhsshim/amihired-proxy"
    mem_limit: 512m
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443

